import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import { getPages } from "@/sanity/sanity-utils";



export const metadata: Metadata = {
  title: "My Portifolio",
  description: "Generated by Nextjs and Sanity.io",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages= await getPages()
  return (
    <html lang="en">
      <body className="bg-custom-dark max-w-3xl mx-auto py-10">
        <header className="flex items-center justify-between">
          <Link href="/" className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold">
          Portifollio          </Link>
          <div className="flex items-center gap-5 text-sm text-gray-300">
            {pages.map((page)=>(
              <Link className="hover:underline" key={page._id} href={`/${page.slug}`}>
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-20">{children}</main></body>
    </html>
  );
}
